name: Update README.md

on:
  workflow_dispatch:
  schedule:
    -  cron: "*/15 * * * *"
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Run
      run: ./aoc
      env:
        SESSION: ${{ secrets.SESSION }}

    - name: Commit README
      run: |
        git config --global user.name 'Enrico Candino'
        git config --global user.email 'enrico.candino@gmail.com'
        if [[ `git status --porcelain` ]]; then
          git commit -am "Automated commit"
          git push
        fi
